nomeCli = input('Digite o nome do cliente:')
diaVenc = input('Digite o dia de vencimento:')
mesVenc = input('Digite o mês de vencimento:')
valorFat = input('Digite o valor da fatura:')
print('Olá,',nomeCli)
print('A sua fatura com vencimento em',diaVenc,'de',mesVenc,'no valor de R$',valorFat,'está fechada.')
